### ISSUE TITLE
Peer2PeerCode Review 12/09/2021

### ISSUE THREAD

**Issue by TheLuisAbarca** [keroloussamy/ToDo-list#8]
Great Work Everyone is doing it into this Project, and there are always ways to improve and make it more awesome.
Here are some ideas about how to improve it:

-  It would be a great idea to use only one template for HTML across all the tests, maybe defining it at the very beginning of the file.
- Another awesome idea may be that you could instead of mock the elements inside the storage, you could mock the local storage object itself.

One big thing that I want to highlight about your development is that I didn't know that way to specify the correct environment with jsdom. :+1:

**Comment by keroloussamy** [comment]
Thanks, @TheLuisAbarca for your review.
